name = "synthetix-sample-integration"
version = "3.3.4"
description = "Synthetix Sample Integration"

[import.synthetixOmnibus]
source ="synthetix-omnibus:3.3.4"

[contract.sample_integration]
artifact = "SampleIntegration"
args = [
    "<%= imports.synthetixOmnibus.imports.system.CoreProxy.address %>",
    "<%= imports.synthetixOmnibus.imports.system.USDProxy.address %>"
]
depends = ["import.synthetixOmnibus"]
