name = "synthetix-sample-integration"
version = "3.1.2"
description = "Synthetix Sample Integration"

[import.synthetixOmnibus]
source ="synthetix-omnibus:latest"

[contract.sample_integration]
artifact = "SampleIntegration"
args = [
    "<%= imports.synthetixOmnibus.contracts.system.CoreProxy %>",
    "<%= imports.synthetixOmnibus.contracts.system.USDProxy %>"
]
depends = ["import.synthetixOmnibus"]