name = "synthetix-sandbox"
version = "0.1"
description = "Synthetix Sandbox"

[setting.user]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.synthetix]
defaultValue="synthetix:latest"

[setting.spotMarket]
defaultValue="spot-market:latest"

[setting.poolId]
defaultValue = "1"

# Provision Collateral Token
[provision.collateralToken]
source = "mintable-token:latest"

# Provision Chainlink Mock for Collateral Token ($2)
[provision.collateralChainink]
source = "chainlink-mock-v3-aggregator:latest"
initialAnswer = "2000000000000000000"

# Provision Synthetix Core and Oracle Manager
[provision.synthetix]
source = "<%= settings.synthetix %>"
owner = "<%= settings.user %>"

# Register Oracle Manager Node for Collateral Token


# Configure Collateral Token as Collateral


# Create Pool
[invoke.createPool]
target = ["system.CoreProxy"]
from = "<%= settings.poolOwner %>"
func = "createPool"
args = [
    "<%= settings.poolId %>",
    "<%= settings.poolOwner %>",
]
depends=["provision.synthetix"]

# Set Pool as 'Preferred'
[invoke.setPreferredPool]
target = ["synthetix.CoreProxy"]
fromCall.func = "owner"
func = "setPreferredPool"
args = [
    "<%= settings.poolId %>",
]
depends=["invoke.createPool"]

# User receives collateral token

# User deposits collateral token

# User delegates to pool

# User mints half of collateral value

# Provision Spot Market
[provision.spotMarket]
source = "<%= settings.spotMarket %>"
owner = "<%= settings.user %>"

# Create snxTKN Synth
[invoke.registerSynth]
target = ["SpotMarketProxy"]
func = "createSynth"
from = "<%= settings.marketOwner %>"
args = ["Synthetic Token", "snxTKN", "<%= settings.marketOwner %>"]
depends = ['provision.spotMarket']
extra.synth_market_id.event = "SynthRegistered"
extra.synth_market_id.arg = 0

# Allow market to deposit TKN collateral

[invoke.registerOracleNode]
target = ["oracle_manager.Proxy"]
func = "registerOracleNode"
from = "<%= settings.marketOwner %>"
# TODO: make this dynamic?
# abi.encode(['address', 'uint256', 'uint8'], ["0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e", 0, 18]);
args = [3, "0x000000000000000000000000d4a33860578de61dbabdc8bfdb98fd742fa7028e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012", []]

extra.snx_eth_oracle_id.event = "NodeRegistered"
extra.snx_eth_oracle_id.arg = 0

[invoke.updateSynthPriceData]
target = ["SpotMarketProxy"]
func = "updatePriceData"
from = "<%= settings.marketOwner %>"
args = ["<%= extras.synth_market_id %>", "<%= extras.snx_eth_oracle_id %>", "<%= extras.snx_eth_oracle_id %>"]

[invoke.addSettlementStrategy]
target = ["SpotMarketProxy"]
func = "addSettlementStrategy"
from = "<%= settings.marketOwner %>"
args = ["<%= extras.synth_market_id %>", { strategyType = 1, settlementDelay = 1, settlementWindowDuration = 120, priceVerificationContract = "<%= settings.chainlink_verification_contract %>", feedId = "ETH-USD", url = "https://mercury-srv.chain.link/client" }]

# initialize wrapper
